### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by boformer** [Katalyst6/CSL.NetworkExtensions#1]
Can you describe what kind of performance issues you are experiencing?

I will investigate.

**Comment by Katalyst6** [comment]
Object.Instantiate is totally killing the CPU...
Line 28 of CSL.NetworkExtensions/Framework/ToolsCSL.cs

https://github.com/Katalyst6/CSL.NetworkExtensions/blob/master/Framework/ToolsCSL.cs

**Comment by boformer** [comment]
Does the performance drop only occur during loading? In that case, performance does not really matter.

What if you use NetInfo.Instantiate? I guess the result is the same.

Maybe the trick is to clone the prefabs before the prefab initialization. 

That solved some issues with LODs in my mod (I am also cloning prefabs).

I can provide the code for that if you want.

**Comment by Katalyst6** [comment]
I would really want to see the code of cloning if possible.

The performance drop is not in the load (and if it does, I dont really care), the drops are happening in the FPS if I have called Object.Instanciate during the loading...

I have created a thread on the Paradox forums that describe all the behaviors:
https://forum.paradoxplaza.com/forum/index.php?threads/network-extensions-dev-unity-help-needed.872377/

**Comment by Katalyst6** [comment]
Also, I am really interested in the Mod you are doing and if it could be added/merged to the Network Extensions. Could you tell me more?

**Comment by boformer** [comment]
The mod I mentioned is cloning building prefabs, not road prefabs.

I am actually working on 2 mods, and both are detouring the same method which will probably cause incompatibilities.

The first one is Building Themes: In the new version that will be released soon, it will be possible to clone existing building prefabs with a different wealth level (e.g. a level1 copy, a level2 copy and a level3 copy). Later I also want to support clones with changed service types (residential in a commercial prefab), which will require the replacement of the AI before it is initialized. 
The code can be found here: https://github.com/boformer/BuildingThemes/blob/master/BuildingThemes/Detour/BuildingInfoDetour.cs#L46-L69

The other mod is a texture pack mod that allows you to replace the texture of buildings (later also props, cars, maybe roads). The code of the mod is very similar. Instead of cloning prefabs, the mod assigns a different texture to the existing prefabs. The problem is that the LOD texture of all buildings is combined in one large texture in the initialization phase (by a magic method that can not be found in the decompiled source). That's why I have to replace the LOD texture before the initialization.

I thought about creating a separate mod/framework that creates the InitializePrefab() hook for all prefab types, which can then be used by other mods. With 2 events for every prefab type:

`onPreInitialization` and `onPostInitialization`

**Comment by Katalyst6** [comment]
Wow, I must admit that your RedirectionHelper is one hell of a trick!
Thanks for the info, I will dig deeper in your code later today to see if I can get anything that can enhance the Network Extensions perfs...

**Comment by Katalyst6** [comment]
I have noticed that the NetInfo Lane Props are the source of all this lag.
If you have any clues how to handle the Props correctly, it would be really appreciated!

{Copied from the Steam thread}
After the instanciation of the NetInfo with Object.Instantiate(originalPrefab.gameObject)
If I do:

```
       foreach (var lane in netInfo.m_lanes)
        {
            lane.m_laneProps = null;
        }
```

...the lag is gone... but so are the Props (i.e. the street lights, lane arrows, etc, etc)

**Comment by boformer** [comment]
Does the instantiate method also create a deep copy of the m_laneProps array? How far does it go?

What if you just set m_laneProps = originalPrefab.m_laneProps?

**Comment by Katalyst6** [comment]
It seems to have a deepcopy process...
But also, if I do assign it from the original, the lag is still present as if those Scriptable objects were being reprocessed...

-------- Original message --------

**Comment by boformer** [comment]
That's really strange. 

My guess is the initialized flag. Is it ever set to true?

**Comment by Katalyst6** [comment]
I ve finally found the bug, it's a matter of attaching correctly the gameobject.transform...
Jeez... it had cost me 3 days of digging throught the engine!

**Comment by boformer** [comment]
Can you show me the code segment you added to fix the problem?

**Comment by Katalyst6** [comment]
Sure, I will deeply remember those lines for a while =P:

https://github.com/Katalyst6/CSL.NetworkExtensions/blob/master/Framework/Extensions/NetInfoExtensions.cs#L22-L24
