### ISSUE TITLE
Use CollossalFramework.Singleton for TextureManager

### ISSUE THREAD

**Issue by boformer** [Katalyst6/CSL.NetworkExtensions#2]
The Singleton class provided by CO is better. It creates a GameObject for the Singleton object, so it shows up in the ModTools Scene Explorer.

Just 2 lines are needed to create a singleton class:

``` c#
using ColossalFramework;

public class TextureManager : Singleton<TextureManager>
{
    // stuff
}
```

Now you can simply use `ThemesManager.instance`. The singleton instance will automatically created by the framework.

**Comment by Katalyst6** [comment]
Really good idea! I'll implement it for the next release!
Thanks for the advice, really appreciated

**Comment by Katalyst6** [comment]
Done! Will be release with the perf update...
